name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        git rm -r $GITHUB_WORKSPACE/*.bin || true
    - name: Run PlatformIO WLED-FastLED esp32dev
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/atuline/WLED/archive/refs/heads/WLED-FastLED.zip -O /tmp/WLEDtemp/mm.zip
        unzip -o /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -name "WLED-*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32dev' >>platformio.ini
        echo 'build_flags = ${env:esp32dev.build_flags} ${common.debug_flags} -D SR_DEBUG -D MIC_LOGGER -D WLED_DISABLE_ESPNOW -D WLED_DEBUG_NTP -D WLED_DEBUG_IMPROV -D WLED_ENABLE_SIMPLE_UI -D WLED_ENABLE_MQTT -D WLED_ENABLE_WEBSOCKETS -D WLED_ENABLE_ADALIGHT -D WLED_ENABLE_PIXART -D WLED_DISABLE_ALEXA -D WLED_DISABLE_HUESYNC -D WLED_DISABLE_2D -D LEDPIN=13 -D AUDIOPIN=15 -D I2S_SDPIN=32 -D DEFAULT_LED_COUNT=66 -D CLIENT_SSID='\''"Kira Wedding Studio"'\'' -D CLIENT_PASS='\''"xincamon"'\'' -D WLED_AP_SSID='\''"Kimob Labs"'\'' -D WLED_AP_PASS='\''"xincamon"'\'' -D WLED_WATCHDOG_TIMEOUT=0 -D USERMOD_AUTO_SAVE -D USERMOD_WORDCLOCK -D USERMOD_ANALOG_CLOCK -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USE_ALT_DISPlAY -D USERMOD_BATTERY -D RGB_ROTARY_ENCODER -D USERMOD_ADS1115' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32dev.lib_deps}' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        echo '  lennarthennigs/ESP Rotary@^1.5.0' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        pio run -e custom_build || pio run -e custom_build || true
    - name: Copy Files WLED-FastLED esp32dev
      run: |
        cd $GITHUB_WORKSPACE
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/build_WLED-FastLED_esp32dev.bin || true
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files WLED-FastLED esp32dev
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/build_WLED-FastLED_esp32dev.bin || true
        git add $GITHUB_WORKSPACE/last_update_date.txt || true
        git commit -m "Commit Custom Build" || true
        git push origin main || true
